## array()创建ndarray数组

In [46]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [42]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))# 输入可以是列表或者元组

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [62]:
#  np.zeros创建一个全是0
zeros_array = np.zeros(5)
print(zeros_array) 

[0. 0. 0. 0. 0.]


In [63]:
# np.ones创建一个全是1的矩阵
ones_matrix = np.ones((3, 3))
print(ones_matrix)
print(np.ones_like(zeros_array))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [45]:
# np.arange创建一个等差数列数组
range_array = np.arange(0, 10, 2)  # 从0到10，步长为2
print(range_array)

[0 2 4 6 8]


In [60]:
# np.full创建以某以元素或数组填充的数组
print(np.full(5,-np.inf))
print(np.full((3,4),[1,4,3,5]))

[-inf -inf -inf -inf -inf]
[[1 4 3 5]
 [1 4 3 5]
 [1 4 3 5]]


### linspace创建等距分布数组
linspace(start,end,num,endpoint)<br>
num:需要取的数量<br>
endpoint:是否要右端点（默认true）<br>
若需右端点，平均每份分d=（end-start）/（num-1）即[start,start+d,..,end]
无需右端点，平均每份分d=（end-start）/ num即[start,start+d,..,end-d]

In [51]:
arr=np.linspace(0,30,5)
print(arr)
arr=np.linspace(0,30,5,endpoint=False)
print(arr)

[ 0.   7.5 15.  22.5 30. ]
[ 0.  6. 12. 18. 24.]


In [59]:
arr0=np.linspace(0,5,6)
print(arr0)
# logspace
# 设结果arr=[a1,...,an],则ai=10^arr0[i],即ai取10的对数后是等距的[10,100,1000]=>[1,2,3]
arr=np.logspace(0,5,6)
print(arr)

[0. 1. 2. 3. 4. 5.]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


## np.random模块

https://zhuanlan.zhihu.com/p/474425448

In [45]:
# np.random.seed设置随机数种子
# np.random.seed(20)
# np.random.seed(None)

### np.random.rand():生成指定维度的的[0,1)范围之间的随机数
输入参数为维度

In [5]:
print(np.random.rand(3)) # 一维
print(np.random.rand(3,4)) #二维

[0.81826786 0.55240935 0.90427147]
[[0.0386031  0.67726865 0.61176765 0.22595259]
 [0.27087174 0.87960217 0.60437458 0.84329482]
 [0.38570471 0.870824   0.4684418  0.66411458]]


### np.random.randn():生成指定维度的服从标准正态分布的随机数
输入参数为维度

In [44]:
print(np.random.randn(3)) # 一维
print(np.random.randn(3,4)) #二维

[0.88389311 0.19586502 0.35753652]
[[-2.34326191 -1.08483259  0.55969629  0.93946935]
 [-0.97848104  0.50309684  0.40641447  0.32346101]
 [-0.49341088 -0.79201679 -0.84236793 -1.27950266]]


### random.randint()生成指定范围和维度的整数
random.randint(low, high=None, size=None, dtype=int)<br>
low:只含low时，生成[0,low)范围整数<br>
high:生成[low,high)范围整数<br>
size：维度形状<br>
np.random.random_integers()：返回范围为[low,high] 闭区间 随机整数；可放回的抽样取数<br>

In [35]:
print(np.random.randint(low=20))
print(np.random.randint(1,10))
print(np.random.randint(1,20,size=(4,3)))

16
5
[[15 16 11]
 [11 17  9]
 [ 8 18 10]
 [ 8 11 13]]


### np.random.random()返回0-1之间指定维度下的随机数
输入参数为维度（size）

In [39]:
print(np.random.random())
print(np.random.random(size=(2,3)))

0.3229514914466709
[[0.45693643 0.4890434  0.73819155]
 [0.76741619 0.35253204 0.00442042]]


## numpy维度和维度查询ndim函数

In [47]:
# 0维，单个数据
a=np.array(527)
print(a,a.ndim)

527 0


In [48]:
# 1维，向量
b=np.array([5,2,7])
print(b,b.ndim)

[5 2 7] 1


In [49]:
# 2维，矩阵
c=np.array([[5,2,7],[7,0,7]])
print(c,c.ndim)

[[5 2 7]
 [7 0 7]] 2


In [50]:
# 3维，堆叠的矩阵
d=np.array([[[1,2,3],[4,5,6]],
            [[6,5,4],[3,2,1]]])
print(d,d.ndim)

[[[1 2 3]
  [4 5 6]]

 [[6 5 4]
  [3 2 1]]] 3


In [51]:
# ndmin指定维数
print(np.array([1,2,3],ndmin=3))

[[[1 2 3]]]


## 元素访问
索引从0开始（可以是负数索引，即-n则倒数第n个）<br>
维度之间逗号分隔：[d_0i,d_1j,...,d_nm]，d_ij即第i维第j个元素。:则代表全部元素<br>
维度划分：括号由外向内分别是0，1，...，n维<br>
[ [ [1 2 3]]]<br>
0 1 2维<br>

In [52]:
arr23=np.array([[1,2,3],
               [4,5,6]])
print(arr23[1,2])
print(arr23[-1,2])
print(arr23[:,1]) #第1维上第1的全部元素，此处即第1列（0开始）的元素

6
6
[2 5]


## 数组裁剪（和python的list一致）
``arr[start:end:step]``<br>
**start**:起始索引（切片包含该元素），不传默认为0 <br>
**end**：结束索引（切片不包含该元素）<br>
**step**：步长，不传默认为1 <br>
支持负数索引

In [53]:
# arange函数,[start,end,step]以逗号分隔
arr7=np.arange(0,7,1) #np.arange(7)
print(arr7)

[0 1 2 3 4 5 6]


In [54]:
print(arr7[3:]) 
print(arr7[:5])
print(arr7[::2])
print(arr7[4:0:-1])

[3 4 5 6]
[0 1 2 3 4]
[0 2 4 6]
[4 3 2 1]


In [55]:
# 2-D数组,维度之间','分隔
arr34=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
print(arr34[1:,2:]) #1:即第1行以后，2：即第2个开始取

[[ 7  8]
 [11 12]]
