# 数组形状

## 数组的形状
数组中每个维度数量

## shape函数获取数组形状

In [2]:
import numpy as np

In [3]:
arr34=np.array([[1,2,3,4],
                [4,5,6,7],
                [7,8,9,10]])
print(arr34.shape)

(3, 4)


In [7]:
arr1=np.array([1,2,3,4,5],ndmin=5)
print(arr1)
print(arr1.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


## reshape重塑数组形状
将数组转换成希望的维度形状（view格式）,重塑前后需要元素的数量相等（1 * 12 -> 4 * 3 or 2 * 2 * 4...但1 * 8不能转换为3 * 3）

In [10]:
arr_12=np.arange(12)
print(arr_12.shape)
arr43=arr_12.reshape(4,3)
arr223=arr43.reshape(2,2,-1) #可以自动计算，-1表示未知维度
print(arr_12.shape) # rehsape不改变原数组形状
# print(arr_12)
print(arr43.shape)
# print(arr43)
print(arr223.shape)
# print(arr223)


(12,)
(12,)
(4, 3)
(2, 2, 3)


In [13]:
# base有值，是view格式
print(arr43.base)
print(arr43.base)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
# -1 的妙用：展平数组
arr23=np.array([[1,2,3],
       [4,5,6]])
arr_6=arr23.reshape(-1)
print(arr_6.shape)

(6,)
