# numpy运算

## 单目运算
数乘：k*arr  
函数：sqrt,sin,cos,log,exp...

In [23]:
import numpy as np

In [24]:
arr=np.arange(1,8)
print(5*arr)
print(np.power(arr,2))
print(np.sin(arr))
print(np.log(arr))

[ 5 10 15 20 25 30 35]
[ 1  4  9 16 25 36 49]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]


## 同维数组双目运算+-*/


In [25]:
arr1=np.arange(1,8)
arr2=np.arange(10,80,10)
print(arr1+arr2)
print(arr1*arr2)

[11 22 33 44 55 66 77]
[ 10  40  90 160 250 360 490]


## 向量点乘dot和矩阵乘法@

In [26]:
print(np.dot(arr1,arr2))
arr1_24=np.arange(1,9).reshape(2,4)
arr2_24=np.arange(10,90,10).reshape(4,2)
print(arr1_24@arr2_24)

1400
[[ 500  600]
 [1140 1400]]


## 降维操作
axis:可以指定轴，默认则展平再求<br><br>
求最大最小：min,max<br>
求最大最小索引：argmin,argmax<br>
求和：sum<br>
求平均值：mean<br>
求中位数：median<br>
方差：var<br>
标准差：std<br>

In [27]:
arr=np.random.randint(1,20,5)
print(arr)
print(np.min(arr))
print(np.argmax(arr))

[12  4 15  6  2]
2
2


In [28]:
arr=np.arange(1,6)
print(arr.mean()) #np.mean(arr)
print(np.median(arr))
print(arr.var()) # np.var(arr)

3.0
3.0
2.0


In [29]:
arr_34=np.arange(12).reshape(3,4)
print(arr_34)
print(arr_34.mean(axis=0))#按列

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4. 5. 6. 7.]


## 广播机制
将数组复制扩充为相同维度在运算  <br>
a+b:<br>
a=[[1],[2],[3]]  =>   a=[[1,1],[2,2],[3,3]]   <br>
b=[[10,20]]      =>   b=[[10,20],[10,20],[10,20]]   <br>

In [30]:
a=np.array([[1],[2],[3]])
b=np.array([[10,20]])
print(a+b)

[[11 21]
 [12 22]
 [13 23]]
