# 基本用法

In [3]:
import pandas as pd
import numpy as np

### Series序列

In [10]:
s1=pd.Series([12,np.nan,24])
print(s1)
s2=pd.Series(['apple','banana','cherry'])
print(s2)

0    12.0
1     NaN
2    24.0
dtype: float64
0     apple
1    banana
2    cherry
dtype: object


### Categorical将数据准换为分类

In [16]:
# 将 citys 列转换为分类类型
citys=['New York', 'London', 'New York', 'Paris', 'Tokyo','Paris']
print(pd.Categorical(citys))

['New York', 'London', 'New York', 'Paris', 'Tokyo', 'Paris']
Categories (4, object): ['London', 'New York', 'Paris', 'Tokyo']


### Timestamp和timerange
date_range:<br>
起始时间：时间戳、字符串等
periods：int型，时长

In [31]:
# 创建一个时间戳对象
st=pd.Timestamp("20231122")
print(st)
d=pd.date_range(st,periods=6) # pd.date_range("20231122",periods=6)
print(d[0])
print(d)

2023-11-22 00:00:00
2023-11-22 00:00:00
DatetimeIndex(['2023-11-22', '2023-11-23', '2023-11-24', '2023-11-25',
               '2023-11-26', '2023-11-27'],
              dtype='datetime64[ns]', freq='D')


### DataFrame

In [56]:
dct={'name':['Alice','Bob','Cindy'],
     'age':[19,21,24],
     'height':[170,185,168],
     'city':pd.Categorical(['New York', 'London', 'New York']),
     'st':d[0]}
df1=pd.DataFrame(dct)
print(df1)
display(df1)

    name  age  height      city         st
0  Alice   19     170  New York 2023-11-22
1    Bob   21     185    London 2023-11-22
2  Cindy   24     168  New York 2023-11-22


name  age  height      city         st
0  Alice   19     170  New York 2023-11-22
1    Bob   21     185    London 2023-11-22
2  Cindy   24     168  New York 2023-11-22

In [58]:
# 返回字典
df1_dct=df1.to_dict()
print(df1_dct)

{'name': {0: 'Alice', 1: 'Bob', 2: 'Cindy'}, 'age': {0: 19, 1: 21, 2: 24}, 'height': {0: 170, 1: 185, 2: 168}, 'city': {0: 'New York', 1: 'London', 2: 'New York'}, 'st': {0: Timestamp('2023-11-22 00:00:00'), 1: Timestamp('2023-11-22 00:00:00'), 2: Timestamp('2023-11-22 00:00:00')}}


查看相关信息：<br>
dtypes查看列的类型<br>
head，tail查看头（尾）x行  <br>
columns查看列名 <br>
index查看索引  <br>
describe查看行数，每列方差等  <br>

In [45]:
df_idx=pd.date_range('20231122',periods=7)
df_data=np.random.randint(1,10,size=(7,5))
print(df_data)
df_col=list('ABCDE')
df=pd.DataFrame(data=df_data,index=df_idx,columns=df_col)
print(df)

[[2 5 5 7 3]
 [5 6 6 7 4]
 [3 2 7 1 5]
 [3 1 4 1 5]
 [5 7 6 9 3]
 [9 3 8 5 8]
 [5 2 1 9 6]]
            A  B  C  D  E
2023-11-22  2  5  5  7  3
2023-11-23  5  6  6  7  4
2023-11-24  3  2  7  1  5
2023-11-25  3  1  4  1  5
2023-11-26  5  7  6  9  3
2023-11-27  9  3  8  5  8
2023-11-28  5  2  1  9  6


In [46]:
print(df1.dtypes)
print(df.dtypes)

name              object
age                int64
height             int64
city            category
st        datetime64[ns]
dtype: object
A    int32
B    int32
C    int32
D    int32
E    int32
dtype: object


In [47]:
# head，tail查看头x行
print(df.head(3))
print(df.tail(3))

            A  B  C  D  E
2023-11-22  2  5  5  7  3
2023-11-23  5  6  6  7  4
2023-11-24  3  2  7  1  5
            A  B  C  D  E
2023-11-26  5  7  6  9  3
2023-11-27  9  3  8  5  8
2023-11-28  5  2  1  9  6


In [55]:
print(df.columns)

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')


In [51]:
print(df.index)

DatetimeIndex(['2023-11-22', '2023-11-23', '2023-11-24', '2023-11-25',
               '2023-11-26', '2023-11-27', '2023-11-28'],
              dtype='datetime64[ns]', freq='D')


In [54]:
print(df.describe())

              A         B         C         D         E
count  7.000000  7.000000  7.000000  7.000000  7.000000
mean   4.571429  3.714286  5.285714  5.571429  4.857143
std    2.299068  2.288689  2.288689  3.408672  1.772811
min    2.000000  1.000000  1.000000  1.000000  3.000000
25%    3.000000  2.000000  4.500000  3.000000  3.500000
50%    5.000000  3.000000  6.000000  7.000000  5.000000
75%    5.000000  5.500000  6.500000  8.000000  5.500000
max    9.000000  7.000000  8.000000  9.000000  8.000000


修改index，columns

In [62]:
df.index=['day1','day2','day3','day4','day5','day6','day7']
df.columns=['Aa','Bb','Cc','Dd','Ee']

# 单独变更列名
# df.rename(index={'day1':'day_one'}) #不生效
df=df.rename(columns={'Aa':'AA'})
print(df.index)
print(df.columns)

Index(['day1', 'day2', 'day3', 'day4', 'day5', 'day6', 'day7'], dtype='object')
Index(['AA', 'Bb', 'Cc', 'Dd', 'Ee'], dtype='object')


### 排序
sort_index()按索引排序<br>
axis:排序维度，行或列<br>
ascending：是否降序<br>

sort_value()按值排序<br>
by:按照哪个列名

In [65]:
data = {
    'C': [3, 1, 4],
    'B': [9, 6, 3],
    'A': [7, 4, 1]
}

df53 = pd.DataFrame(data,index=[2,0,1])

# 按照行索引进行升序排序
print(df53)
print(df53.sort_index())
# 按照列名索引进行升序排序
print(df53.sort_index(axis=1))



   C  B  A
2  3  9  7
0  1  6  4
1  4  3  1
   C  B  A
0  1  6  4
1  4  3  1
2  3  9  7
   A  B  C
2  7  9  3
0  4  6  1
1  1  3  4


In [66]:
print(df53.sort_values(by='A'))

   C  B  A
1  4  3  1
0  1  6  4
2  3  9  7
